version: '2'
services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "8000:8080"
    volumes:
      - ./conf/docker_nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8080"
    volumes:
      - ./:/opt/app:rw
    depends_on:
      - nginx
